/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2017 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.locationupdatesservice;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

@Kroll.module(name = "Locationupdatesservice", id = "ti.locationupdatesservice")
public class LocationupdatesserviceModule extends KrollModule {

	// Standard Debugging variables
	private static final String LCAT = "TiGeoLogger";

	private static String dbName = "geologger";
	private static String notChannel = "channel1";
	private static String notIcon = null;
	private static String notTitle = "";
	private static int interval = 0;
	private static int duration = 0;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public LocationupdatesserviceModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is
		// created
	}

	// Methods
	@Kroll.method
	public void config(KrollDict opts) {
		if (opts.containsKeyStartingWith("dbName"))
			dbName = opts.getString("dbName");
		if (opts.containsKeyStartingWith("notification")
				&& opts.get("notification") instanceof KrollDict) {
			KrollDict notification = opts.getKrollDict("notification");
			if (notification.containsKeyAndNotNull("channel"))
				notChannel = notification.getString("channel");
			if (notification.containsKeyAndNotNull("icon"))
				notIcon = notification.getString("icon");
			if (notification.containsKeyAndNotNull("title"))
				notTitle = notification.getString("title");
		}
		dbName = opts.getString("dbName");

	}

	@Kroll.method
	public void start(KrollDict opts) {
		if (opts.containsKeyStartingWith("dbName"))
			dbName = opts.getString("dbName");
		if (opts.containsKeyStartingWith("notification")
				&& opts.get("notification") instanceof KrollDict) {
			KrollDict notification = opts.getKrollDict("notification");
			if (notification.containsKeyAndNotNull("channel"))
				notChannel = notification.getString("channel");
			if (notification.containsKeyAndNotNull("icon"))
				notIcon = notification.getString("icon");
			if (notification.containsKeyAndNotNull("title"))
				notTitle = notification.getString("title");
		}
		dbName = opts.getString("dbName");

	}

	@Kroll.method
	public void stop() {

	}

	@Kroll.setProperty
	public void setExampleProp(String value) {
		Log.d(LCAT, "set example property: " + value);
	}

}
